In [1]:
import numpy as np

In [33]:
A = np.array([[3, 2, -4],
              [2, 3, 3],
              [5, -3, 1]], dtype=float)

In [28]:
b = np.array([3, 15, 14], dtype=float)

In [29]:
scale_factors = np.max(np.abs(A), axis=1)
scale_factors

array([4., 3., 5.])

In [30]:
def gaussian_partial_pivoting(A, b):

    n = len(b)

    indices = np.arange(n)

    for i in range(n):
        max_row = np.argmax( np.abs(  A[ indices[i:] ,i] )) + i
        if A[ indices[max_row] ,i] == 0:
            raise ValueError("A is singulr or nearly singular")
        
        if max_row != i:
            indices[ [i, max_row]] = indices[ [max_row, i] ]
        
        for j in range(i+1,n):
            factor = A[indices[j],i] / A[indices[i], i]
            A[indices[j], i:] -= factor * A[indices[i], i:]
            b[indices[j]] -= factor * b[indices[i]]

    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (b[indices[i]] - A[indices[i], i+1:] @ x[i+1:]) / A[indices[i],i]

    return x

In [23]:
np.arange(4)

array([0, 1, 2, 3])

In [31]:
gaussian_partial_pivoting(A, b)

array([3., 1., 2.])

In [9]:
def gaussian_partial_scaled_pivoting(A, b):

    n = len(b)

    indices = np.arange(n)

    scale_factors = np.max(np.abs(A), axis=1)

    for i in range(n):
        max_row = np.argmax( np.abs(  A[ indices[i:] ,i] ) / scale_factors[indices[i:]] ) + i
        if A[ indices[max_row] ,i] == 0:
            raise ValueError("A is singulr or nearly singular")
        
        if max_row != i:
            indices[ [i, max_row]] = indices[ [max_row, i] ]
        
        for j in range(i+1,n):
            factor = A[indices[j],i] / A[indices[i], i]
            A[indices[j], i:] -= factor * A[indices[i], i:]
            b[indices[j]] -= factor * b[indices[i]]

        print(A[indices, :])
        
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (b[indices[i]] - A[indices[i], i+1:] @ x[i+1:]) / A[indices[i],i]

    return x

In [32]:
A

array([[ 0.        ,  0.        , -6.95238095],
       [ 0.        ,  4.2       ,  2.6       ],
       [ 5.        , -3.        ,  1.        ]])

In [36]:
gaussian_partial_scaled_pivoting(A.copy(),b)

[[ 1.23616511e+02  1.00812569e+01  5.66190617e+00 ...  1.92120123e+00
   1.78282348e+00  7.86607480e+00]
 [ 0.00000000e+00 -2.70702109e+00 -2.50610496e+00 ...  3.74423951e-01
  -2.85054254e-02  9.42503916e+00]
 [ 0.00000000e+00 -1.75611707e+00  3.86512257e+00 ...  1.84018324e+01
   7.00810353e+01  3.64907797e+00]
 ...
 [ 0.00000000e+00 -3.82025746e-01  6.60147467e+01 ...  2.55282859e+00
   9.89941324e-01  5.53899314e+00]
 [ 7.10542736e-15  5.99850639e+00  5.21049720e-01 ...  1.27104910e+01
   3.09676375e+01  3.54848410e+01]
 [ 0.00000000e+00  8.49558060e-01  3.03749205e+00 ...  3.58554052e+00
   4.01396040e+01  4.75560920e+00]]
[[ 1.23616511e+02  1.00812569e+01  5.66190617e+00 ...  1.92120123e+00
   1.78282348e+00  7.86607480e+00]
 [ 0.00000000e+00  1.41103060e+02  2.76874577e+00 ...  5.66236180e+00
   7.73266896e+00  1.49246477e+00]
 [ 0.00000000e+00 -2.22044605e-16  3.89958137e+00 ...  1.84723041e+01
   7.01772732e+01  3.66765264e+00]
 ...
 [ 0.00000000e+00  0.00000000e+00  6.6022242

array([-0.01333207,  0.00101011, -0.01185684, -0.00696413, -0.01664498,
       -0.00060954, -0.02819568,  0.00230712,  0.00925852,  0.00526733,
       -0.00776705, -0.00163726,  0.01717665, -0.00862775,  0.00587618,
        0.01861679,  0.01147083, -0.00373744, -0.00311294,  0.00368208,
       -0.00924393, -0.00394539,  0.01352392,  0.00180512,  0.0069987 ,
        0.00556083,  0.01641761,  0.00756513,  0.00451598,  0.0134993 ,
       -0.00744165,  0.00449318, -0.00453275,  0.0072828 , -0.00044369,
       -0.01443314,  0.01180665,  0.01169573, -0.02570742,  0.01190538,
       -0.00327482, -0.00072798,  0.00678379,  0.01499118, -0.00548224,
       -0.01223916, -0.0019477 , -0.00830734,  0.00401093,  0.01113645])

In [34]:
A = np.exp(5 * np.random.rand(50,50))
b = np.random.rand(50)


In [35]:
gaussian_partial_pivoting(A.copy(),b.copy()) - np.linalg.solve(A,b)

array([ 5.03069808e-17,  6.50521303e-18,  5.55111512e-17, -4.68375339e-17,
        3.46944695e-18,  9.02056208e-17,  4.85722573e-17, -1.14491749e-16,
        3.98986399e-17, -3.38271078e-17,  2.42861287e-17, -4.01154804e-17,
        1.04083409e-17, -3.46944695e-18,  1.12757026e-17, -1.45716772e-16,
       -1.90819582e-17, -9.93129190e-17,  1.07552856e-16, -2.12503626e-17,
        6.93889390e-17,  3.29597460e-17, -7.11236625e-17, -4.77048956e-17,
        8.93382590e-17,  5.20417043e-18, -7.63278329e-17,  2.86229374e-17,
        6.76542156e-17, -3.46944695e-17,  3.29597460e-17,  4.07660017e-17,
        3.20923843e-17, -1.11889664e-16,  2.87313576e-18,  6.24500451e-17,
        2.08166817e-17,  6.24500451e-17,  3.46944695e-17,  5.20417043e-18,
       -1.51788304e-17, -2.12503626e-17,  6.76542156e-17, -7.28583860e-17,
        3.46944695e-18,  2.25514052e-17, -1.30104261e-18,  2.77555756e-17,
       -6.76542156e-17, -6.24500451e-17])

In [13]:
A.shape

(50, 50)

In [15]:
def inverse_by_gaussian(A):
    n = A.shape[0]

    AI = np.hstack((A , np.eye(n, dtype=float)))

    for i in range(n):
        max_row = np.argmax( np.abs( AI[i:,i])) + i
        if AI[max_row, i] == 0:
            raise ValueError("A is nearly singular")
        
        if max_row != i:
            AI[[i,max_row]] = AI[[max_row,i]]

        AI[i] = AI[i] / AI[i,i]

        for j in range(n):
            if j != i:
                AI[j] -= AI[j,i] * AI[i]

    return AI[:,n:]


        
    

In [41]:
A = np.array([[3, 2, -4],
              [2, 3, 3],
              [5, -3, 1]], dtype=float)

In [42]:
np.linalg.inv(A)

array([[ 0.08219178,  0.06849315,  0.12328767],
       [ 0.0890411 ,  0.15753425, -0.11643836],
       [-0.14383562,  0.13013699,  0.03424658]])

In [40]:
inverse_by_gaussian(A)

array([[ 0.08219178,  0.06849315,  0.12328767],
       [ 0.0890411 ,  0.15753425, -0.11643836],
       [-0.14383562,  0.13013699,  0.03424658]])

In [20]:
def determinant(A):
    n = A.shape[0]

    det = 1.

    for i in range(n):
        max_row = np.argmax( np.abs( A[i:,i])) + i
        if A[max_row, i] == 0:
            return 0
        
        if max_row != i:
            A[[i,max_row]] = A[[max_row,i]]
            det *= -1

        for j in range(i+1,n):
            A[j,i:] -= (A[j,i]/A[i,i]) * A[i,i:]

    for i in range(n):
        det *= A[i,i]

    return det

In [21]:
np.linalg.det(A)

146.0

In [22]:
determinant(A.copy()) - np.linalg.det(A)

-2.842170943040401e-14