In [1]:
import numpy as np

In [34]:
A = np.array([[3, 2, -4],
              [2, 3, 3],
              [5, -3, 1]], dtype=float)

In [35]:
b = np.array([3, 15, 14], dtype=float)

In [25]:
scale_factors = np.max(np.abs(A), axis=1)
scale_factors

array([4., 3., 5.])

In [9]:
B

array([[ 0.08219178,  0.06849315,  0.12328767],
       [ 0.0890411 ,  0.15753425, -0.11643836],
       [-0.14383562,  0.13013699,  0.03424658]])

In [28]:
def gaussian_partial_pivoting(A, b):

    n = len(b)

    indices = np.arange(n)

    for i in range(n):
        max_row = np.argmax( np.abs(  A[ indices[i:] ,i] )) + i
        if A[ indices[max_row] ,i] == 0:
            raise ValueError("A is singulr or nearly singular")
        
        if max_row != i:
            indices[ [i, max_row]] = indices[ [max_row, i] ]
        
        for j in range(i+1,n):
            factor = A[indices[j],i] / A[indices[i], i]
            A[indices[j], i:] -= factor * A[indices[i], i:]
            b[indices[j]] -= factor * b[indices[i]]

    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (b[indices[i]] - A[indices[i], i+1:] @ x[i+1:]) / A[indices[i],i]

    return x

In [29]:
gaussian_partial_pivoting(A, b)

array([3., 1., 2.])

In [32]:
def gaussian_partial_scaled_pivoting(A, b):

    n = len(b)

    indices = np.arange(n)

    scale_factors = np.max(np.abs(A), axis=1)

    for i in range(n):
        max_row = np.argmax( np.abs(  A[ indices[i:] ,i] ) / scale_factors[indices[i:]] ) + i
        if A[ indices[max_row] ,i] == 0:
            raise ValueError("A is singulr or nearly singular")
        
        if max_row != i:
            indices[ [i, max_row]] = indices[ [max_row, i] ]
        
        for j in range(i+1,n):
            factor = A[indices[j],i] / A[indices[i], i]
            A[indices[j], i:] -= factor * A[indices[i], i:]
            b[indices[j]] -= factor * b[indices[i]]

        print(A[indices, :])
        
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (b[indices[i]] - A[indices[i], i+1:] @ x[i+1:]) / A[indices[i],i]

    return x

In [36]:
gaussian_partial_scaled_pivoting(A,b)

[[ 5.  -3.   1. ]
 [ 0.   4.2  2.6]
 [ 0.   3.8 -4.6]]
[[ 5.         -3.          1.        ]
 [ 0.          4.2         2.6       ]
 [ 0.          0.         -6.95238095]]
[[ 5.         -3.          1.        ]
 [ 0.          4.2         2.6       ]
 [ 0.          0.         -6.95238095]]


array([3., 1., 2.])

In [49]:
A = np.exp(5 * np.random.rand(50,50))
b = np.random.rand(50)


In [52]:
gaussian_partial_pivoting(A.copy(),b.copy()) - np.linalg.solve(A,b)

array([ 8.67361738e-18,  5.20417043e-17, -6.24500451e-17,  0.00000000e+00,
       -5.72458747e-17, -5.55111512e-17, -1.21430643e-16,  2.39391840e-16,
        5.55111512e-17, -2.77555756e-16, -6.93889390e-18,  2.91433544e-16,
        7.45931095e-17,  1.06034972e-16,  6.59194921e-17,  1.19695920e-16,
       -1.38777878e-16, -2.01227923e-16,  1.59594560e-16,  1.00613962e-16,
        1.94289029e-16, -2.08166817e-17, -3.93023288e-18,  2.08166817e-17,
       -3.46944695e-17,  1.90819582e-17, -7.63278329e-17,  5.20417043e-17,
       -5.89805982e-17, -7.63278329e-17, -1.31838984e-16, -4.85722573e-17,
       -5.55111512e-17, -2.90566182e-17,  4.16333634e-17,  1.52655666e-16,
       -2.15105711e-16,  4.64038530e-17,  4.59701721e-17, -1.23165367e-16,
        5.20417043e-18, -1.07552856e-16,  4.16333634e-17, -1.24900090e-16,
       -2.77555756e-17,  1.73472348e-16, -5.50774704e-17,  3.46944695e-18,
        4.85722573e-17,  5.20417043e-18])

In [53]:
A.shape

(50, 50)

In [61]:
def inverse_by_gaussian(A):
    n = A.shape[0]

    AI = np.hstack((A , np.eye(n, dtype=float)))

    for i in range(n):
        max_row = np.argmax( np.abs( AI[i:,i])) + i
        if AI[max_row, i] == 0:
            raise ValueError("A is nearly singular")
        
        if max_row != i:
            AI[[i,max_row]] = AI[[max_row,i]]

        AI[i] = AI[i] / AI[i,i]

        for j in range(n):
            if j != i:
                AI[j] -= AI[j,i] * AI[i]

    return AI[:,n:]


        
    

In [70]:
A = np.array([[3, 2, -4],
              [2, 3, 3],
              [5, -3, 1]], dtype=float)

In [56]:
np.linalg.inv(A)

array([[ 0.08219178,  0.06849315,  0.12328767],
       [ 0.0890411 ,  0.15753425, -0.11643836],
       [-0.14383562,  0.13013699,  0.03424658]])

In [62]:
inverse_by_gaussian(A)

array([[ 0.08219178,  0.06849315,  0.12328767],
       [ 0.0890411 ,  0.15753425, -0.11643836],
       [-0.14383562,  0.13013699,  0.03424658]])

In [67]:
def determinant(A):
    n = A.shape[0]

    det = 1.

    for i in range(n):
        max_row = np.argmax( np.abs( A[i:,i])) + i
        if A[max_row, i] == 0:
            raise ValueError("A is nearly singular")
        
        if max_row != i:
            A[[i,max_row]] = A[[max_row,i]]
            det *= -1

        for j in range(i+1,n):
            A[j,i:] -= (A[j,i]/A[i,i]) * A[i,i:]

    for i in range(n):
        det *= A[i,i]

    return det

In [72]:
np.linalg.det(A)

146.0

In [71]:
determinant(A.copy()) - np.linalg.det(A)

-2.842170943040401e-14